version: '3.8'

services:
    db:
        container_name: "${PROJECT_NAME}_mysql"
        stop_grace_period: 30s
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - symfony

    php:
        container_name: "${PROJECT_NAME}_php"
        environment:
            PHP_XDEBUG: 1
            PHP_XDEBUG_MODE: debug
            PHP_IDE_CONFIG: serverName=phpstorm
            PHP_XDEBUG_IDEKEY: "phpstorm"
            PHP_XDEBUG_CLIENT_HOST: 172.17.0.1 # Linux
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./symfony/:/var/www/symfony/
        networks:
            - symfony

    nginx:
        container_name: "${PROJECT_NAME}_nginx"
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./symfony/:/var/www/symfony/
        depends_on:
            - php
        ports:
            - 80:80
            - 443:443
        networks:
            - symfony

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: "${PROJECT_NAME}_phpmyadmin"
        environment:
            PMA_HOST: ${MYSQL_HOST}
            PLOAD_LIMIT: 1G
        depends_on:
            - db
        restart: always
        ports:
            - 8081:80
        networks:
            - symfony

volumes:
    db_app:

networks:
    symfony:
