<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKjMKK0R\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKjMKK0R/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKjMKK0R.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKjMKK0R\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKjMKK0R\App_KernelDevDebugContainer([
    'container.build_hash' => 'KjMKK0R',
    'container.build_id' => '226bfc96',
    'container.build_time' => 1626611097,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKjMKK0R');
