<?php

namespace ContainerKjMKK0R;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubscribersListControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sergeydrak\SubscriptionBundle\Controller\SubscribersListController' shared autowired service.
     *
     * @return \Sergeydrak\SubscriptionBundle\Controller\SubscribersListController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/.bundles/SubscriptionBundle/src/Controller/SubscribersListController.php';

        $container->services['Sergeydrak\\SubscriptionBundle\\Controller\\SubscribersListController'] = $instance = new \Sergeydrak\SubscriptionBundle\Controller\SubscribersListController(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->services['Sergeydrak\\SubscriptionBundle\\Controller\\WriterController'] ?? $container->load('getWriterControllerService')), ($container->services['Sergeydrak\\SubscriptionBundle\\Controller\\RiderController'] ?? $container->load('getRiderControllerService')), ($container->services['Sergeydrak\\SubscriptionBundle\\Controller\\CoderController'] ?? $container->load('getCoderControllerService')));

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('Sergeydrak\\SubscriptionBundle\\Controller\\SubscribersListController', $container));

        return $instance;
    }
}
