controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

subscription_bundle:
    resource: '@SubscriptionBundle/config/routes.yaml'
