<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD31YT0V\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD31YT0V/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerD31YT0V.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerD31YT0V\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerD31YT0V\App_KernelTestDebugContainer([
    'container.build_hash' => 'D31YT0V',
    'container.build_id' => 'a8ad5f35',
    'container.build_time' => 1626609526,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD31YT0V');
