<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\UserAuthSecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\UserAuthSecurityController::logout'], [], [['text', '/logout']], [], []],
    'subscribers_list' => [[], ['_controller' => 'Sergeydrak\\SubscriptionBundle\\Controller\\SubscribersListController::index'], [], [['text', '/subscribers']], [], []],
    'subscription_form_viiew' => [[], ['_controller' => 'Sergeydrak\\SubscriptionBundle\\Controller\\SubscriptionFormViewController::index'], [], [['text', '/']], [], []],
];
