<?php

namespace ContainerD31YT0V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubscriptionTypeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'Sergeydrak\SubscriptionBundle\Form\SubscriptionType' shared autowired service.
     *
     * @return \Sergeydrak\SubscriptionBundle\Form\SubscriptionType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/.bundles/SubscriptionBundle/src/Form/SubscriptionType.php';

        return $container->privates['Sergeydrak\\SubscriptionBundle\\Form\\SubscriptionType'] = new \Sergeydrak\SubscriptionBundle\Form\SubscriptionType(($container->services['Sergeydrak\\SubscriptionBundle\\Controller\\RiderController'] ?? $container->load('getRiderControllerService')));
    }
}
